### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by DerpySlurrpe** [snipergaming888/fnf-swift-engine#10]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
chart editor crashes once i pressed 7 found this in the console

SwiftEngine.js:135323 Uncaught [lime.utils.Assets] ERROR: There is no TEXT asset with an ID of "assets/data/stageList.txt"
__handleError @ SwiftEngine.js:135323
__broadcastEvent @ SwiftEngine.js:135146
__onLimeRender @ SwiftEngine.js:136169
dispatch @ SwiftEngine.js:114234
handleApplicationEvent @ SwiftEngine.js:5904

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

Using Chrome OS Chrome
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
HTML5 
## What version of the game are you using? Look in the bottom left corner of the main menu.
latest version as of now...

**Comment by snipergaming888** [comment]
let me run some test real quick.

**Comment by snipergaming888** [comment]
> let me run some tests real quick.

I have found no bugs relating to the stage/stagetext in HTML5. if this problem persists, make sure your stageList.txt is in the data folder. if compiling, check both preload/data and data. (when exported)

**Comment by snipergaming888** [comment]
> > let me run some tests real quick.
> 
> I have found no bugs relating to the stage/stagetext in HTML5. if this problem persists, make sure your stageList.txt is in the data folder. if compiling, check both preload/data and data. (when exported)

oh yeah and the charting state crashes anyway cuz of the events tab code, gotta fix that.
