### ISSUE TITLE
Question:  Is there gona be html5 port?

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [snipergaming888/fnf-swift-engine#11]
## What is your question?
Since you do work on the html5 port can you publish it?

**Comment by snipergaming888** [comment]
I update the engine so frequently that there would be no point in uploading a version to my site as it would be outdated in a few days/weeks. however, you can compile it yourself. if I ever stop updating it, I will most likely upload it.

**Comment by LEVIXDDLMAO** [comment]
Can you port something for me?

**Comment by snipergaming888** [comment]
> Oh okay, and how do you do the tags? I tried so much cant figure it out

if your talking about GitHub tags, there is a button up top that you need to click, then type in the name of the tag.

**Comment by snipergaming888** [comment]
> Can you port something for me?

yeah depends on what is is tho

**Comment by LEVIXDDLMAO** [comment]
https://github.com/LEVIXDDLMAO/OnlineVS_Source_Psych
