### ISSUE TITLE
Bug Report: crash when entering story mode and freeplay

### ISSUE THREAD

**Issue by 0-skid** [snipergaming888/fnf-swift-engine#12]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows `x86_64`

## What version of the game are you using? Look in the bottom left corner of the main menu.
v1.6.3

## Please describe your issue. Provide extensive detail and images if possible.
the downloaded build from gb always crashes when entering story mode or freeplay.

**Comment by snipergaming888** [comment]
ldk how that happens but see if it happens with 1.6.4.

**Comment by snipergaming888** [comment]
> ldk how that happens but see if it happens with 1.6.4.

I have checked and it seems as if there is nothing wrong with either state, I believe you might have missing assets or insufficient RAM.

**Comment by 0-skid** [comment]
ah
