### ISSUE TITLE
Question:  yo homie where is the web port??

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [snipergaming888/fnf-swift-engine#7]

**Comment by lin0de** [comment]
y'know what fuck it i'll make it

**Comment by snipergaming888** [comment]
anyone can compile the source and upload it to a web server. I'm not doing cuz I update my engine to often.

**Comment by snipergaming888** [comment]
just read the project.xml so you know what stuff you will need to download to compile.

**Comment by snipergaming888** [comment]
you may also need polys MP4 code if I ever release the week7 build
