### ISSUE TITLE
Question:  Do i need windows to port shit in hmtl5 i want to know my windows 11 isn't working 

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [snipergaming888/fnf-swift-engine#8]
## What is your question?
please help

**Comment by snipergaming888** [comment]
You need any operating system that can download all the packages to compile the game. Read the FNF source code compiling guide, and make sure that you also fetch these haxelibs:
haxelib name="flixel-ui"
haxelib name="newgrounds"
haxelib name="faxe" if='switch'
haxelib name="actuate"
haxelib name="extension-webm" if="desktop"
haxelib name="polymod"/>
haxelib name="discord_rpc" if="desktop"
