### ISSUE TITLE
Enhancement: Week 7

### ISSUE THREAD

**Issue by daisukidaisy** [snipergaming888/fnf-swift-engine#9]
I don't know if you've heard but Week 7 assets are no longer restricted. You can add Week 7 now.

**Comment by snipergaming888** [comment]
> I don't know if you've heard but Week 7 assets are no longer restricted. You can add Week 7 now.

I will release my week 7 build once I update the version its on and fix HTML5 videos.

**Comment by snipergaming888** [comment]
btw I am keeping this open until I add week7.

**Comment by snipergaming888** [comment]
> I don't know if you've heard but Week 7 assets are no longer restricted. You can add Week 7 now.

https://github.com/snipergaming888/fnf-swift-engine-week7
